### ISSUE TITLE
Travis-CI Testing with Multiple Ruby Versions

### ISSUE THREAD

**Issue by defuse** [defuse/yescrypt#18]
Does travis-ci have multi-language support yet? If not, how can we hack it to run the tests with multiple Ruby versions? Maybe we can apt-get install rvm and all of the rubies we care about and then do the switching ourselves in a script... but then we'll have to make sure it doesn't re-run for every PHP version.

**Comment by defuse** [comment]
I spent some time this morning trying to figure this out. Unfortunately, I couldn't figure out how to install more recent versions of PHP (5.5, 5.6) while in the ruby-language environment. We'll have to figure out exactly what apt-get commands to use to get them (maybe use a php5 ppa). Hopefully we won't have to resort to wgetting .debs or building from source.

It would be really great to get this working, because then we could split it into its own `travis-multilanguage` repository, and we could give everyone easy access to multiple-language multiple-version testing. That would be really useful for my password hashing code.

**Comment by defuse** [comment]
Another way to do this would be to have `yescrypt-ruby`, `yescrypt-php`, `yescrypt-python`, ... repositories that automatically track this one, and just change the `.travis.yml`. But that's just ridiculous.

**Comment by defuse** [comment]
Turns out it _is_ supported, as @solarce (no relation) told me on twitter. And now it works!

**Comment by defuse** [comment]
Oh, no, apparently that doesn't work. Looks like those things just change the travis-ci UI, and we have to install the things we want ourselves???

**Comment by solarce** [comment]
@defuse if you look at the details in https://travis-ci.org/defuse/yescrypt/builds/68053775 you can see that it is running the matrix but the [PHP 5.4](https://travis-ci.org/defuse/yescrypt/jobs/68053791) and [PHP 5.3](https://travis-ci.org/defuse/yescrypt/jobs/68053792) builds failed, while [PHP 5.6](https://travis-ci.org/defuse/yescrypt/jobs/68053789) is still running

**Comment by defuse** [comment]
@solarce Yes, build is working as I would expect for PHP. But I think all of the Ruby versions are running off the default version (I expected 1.8.7 to fail). Let me confirm more carefully.

**Comment by solarce** [comment]
@defuse I see now that the builds labeled ruby still ran the php tests. I am not sure if we support multiple languages in the build matrix but I will look into it, as this is an understandable use case

**Comment by defuse** [comment]
@solarce Yeah, they ran with whichever version of Ruby comes with the default environment. To clarify, the goal is: for each PHP version, run _just_ the PHP test, and then for each Ruby version, run just the Ruby test, i.e. there should never be any PHP and Ruby running within the same "instance" (not sure what the correct terminology is), if that matters.

**Comment by solarce** [comment]
I looked into this more and at the moment we don't support multiple built-in language keys inside a build matrix.

However, `rvm` is included in our PHP language image, so you could put rvm commands in your ruby test script to have it install ruby, any gems you need, and then run your tests.

**Comment by defuse** [comment]
Superseded by #24.
