### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by dbakker** [defuse/yescrypt#29]
Your project looks pretty useful!

But for anyone to be able to use it you should add under which license they can do so (e.g. something like [the MIT license](https://github.com/twbs/bootstrap/blob/master/LICENSE)).

**Comment by solardiz** [comment]
Right now, some source files have license statements in them, some don't. And there's no license for the project as a whole. This should in fact be corrected. Where possible (no uses of differently-licensed third-party code), I suggest 0-clause BSD as e.g. `yescrypt-common.c` uses.

**Comment by defuse** [comment]
Added 0-clause BSD license
